# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo
#添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: Home
    url: /
  archives:
    url: /archives/
  tags:
    url: /tags/
  github:
    url: https://github.com/methol
    target: _blank
  # weibo:
  #   url: http://www.weibo.com/ysweb
  #   target: _blank
  # link:
  #   text: 公益404
  #   url: /404

rss: https://blog-static.tuzhihao.com/atom.xml

#你的头像url
avatar: https://blog-static.tuzhihao.com/img/avatar.webp

# email
email: methol@tuzhihao.com

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#3F51B5'

# 页面标题
tags_title: Tags
archives_title: Archives
categories_title: Categories

# 文章截断
excerpt_render: true
# excerpt_length: 200
# excerpt_link: 阅读全文...
mathjax: false
archive_yearly: false

#是否开启分享
share: false

#是否开启打赏，关闭 reward: false
reward:
  title: 谢谢大爷~
  wechat: /img/wechat.png     #微信，关闭设为 false
  alipay: /img/alipay.png     #支付宝，关闭设为 false

#是否开启搜索
search: true

#是否大屏幕下文章页隐藏导航
hideMenu: false

#是否开启toc
# toc: false
toc:
  list_number: true  # 是否显示数字排序

# 文章页留言内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
postMessage:

#站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# Miscellaneous
google_analytics: true
google_site_verification: UA-62589762-1

# less
less:
  compress: true
  paths:
    - source/css/style.less

# 以下评论插件开启一个即可
# 是否开启多说评论，填写你在多说创建的站点二级域名
duoshuo: false
# 是否开启多说评论计数（该服务不稳定）
duoshuo_count: false
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
disqus_shortname: false
# 是否开启友言评论, 填写友言用户id
uyan_uid: false
# 是否开启网易云跟帖， 填写app sdk中的app key
wangyi_ygt: false
# 是否使用 gitment，https://github.com/imsun/gitment
gitment: false
# gitment:
#   owner:
#   repo:
#   client_id:
#   client_secret:

# Valine Comment system. https://valine.js.org
valine:
  enable: true # 如果你想使用valine，请将值设置为 true
  appId:  hVcmQ7QU9KPpWXyBiQCHCJEV-gzGzoHsz
  appKey: dPzReSudS4K4RpSSh7qGfBpW
  notify: false # Mail notify
  verify: false # Verify code
  avatar: mm # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder:  # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 100 # comment list page size

# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: https://tuzhihao.com

# 版权起始年份
since_year: 2015

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: false

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: Total uv：
  site_pv: Total pv：

# 动态定义title
#title_change:
#  normal:
#  leave:

# 设置为 true 发布后将使用 unpkg cdn
cdn_url: https://blog-static.tuzhihao.com

# 设置为 true 将使用 lightbox render 图片
lightbox: true

# icp备案号  ICP_license: 京ICP备1234556号-1
ICP_license: 鄂ICP备15021398号 | 鄂公网安备 42011102000434号
